project_id: ENV['CROWDIN_PROJECT_ID']
api_token: ENV['CROWDIN_PERSONAL_TOKEN']
base_path: '.'
preserve_hierarchy: true

files:
  - source: '/config/locales/en/**/*.yml'
    translation: '/config/locales/%two_letters_code%/%original_file_name%'