name: Docker compose build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        run: |
          docker compose up --build -d
          docker compose exec web rails db:setup
          docker compose exec web rails db:seed
          docker compose exec web rails runner "User.pluck(:id)"

 
